
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    # ports:
    #   - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    environment:
      - DATABASE_URL=mongodb://mongo:27017
    volumes:
      - mongo_volume_data:/data/db
    networks:
      - my-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8082:8082
    # environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/myDatabase
      # ME_CONFIG_BASICAUTH: false
    networks:
      - my-network
  # redis_insight:
  #   image: redislabs/redisinsight:1.14.0
  #   container_name: redis_insight
  #   restart: always
  #   ports:
  #     - 8001:8001
  #   volumes:
  #     - redis_insight_volume_data:/db
  
  app:
    container_name: ideanest-backend
    build: .
    ports:
      - "3000:3000"  # Map container port to host port
    network_mode: "bridge"
    environment:
      - DATABASE_URL=mongodb://mongo:27017
      - SALT_ROUNDS =6
      - SECRET_KEY=secret
      - REFRESH_TOKEN_SECRET_KEY=secret
    depends_on:
      - mongo
      - redis
networks:
  my-network:
    driver: bridge
volumes:
  redis_volume_data:
  mongo_volume_data:
  # redis_insight_volume_data: